# Generated by Django 4.2.11 on 2024-04-12 17:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_referrals'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='referrals',
        ),
        migrations.CreateModel(
            name='Referrals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals_author', to=settings.AUTH_USER_MODEL, verbose_name='На кого подписался')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals_user', to=settings.AUTH_USER_MODEL, verbose_name='Подписчик')),
            ],
            options={
                'verbose_name': 'Реферал',
                'verbose_name_plural': 'Рефералы',
                'db_table': 'referrals',
                'ordering': ['-id'],
            },
        ),
    ]
