# Generated by Django 4.2.11 on 2024-04-15 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_referrals_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
    ]
